name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/DevOps-Assignment

            git pull

            cd backend
            pm2 restart fastapi-backend

            cd ..
            cd frontend
            npm run build
            pm2 restart frontend

            sudo systemctl restart nginx
